
CREATE TABLE [dbo].[Departements](
    [depCode] [int] NOT NULL,
    [nom] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Departements] PRIMARY KEY CLUSTERED 
(
    [depCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
